stopwords = ["first", "weeks", "finally", "lot", "likely", "regarding", "keep", "today", "much", "like",
                     "1",
                     "indeed", "current", "592452720", "decided", "592452420", "many", "could", "8", "2", "get",
                     "quite",
                     "would", "rather", "went", "thru", "found", "coming", "11", "4", "2017", "taken",
                     "still",
                     "means", "less", " setting", "17", "previously", "592452320", "sent", "may", "see", "said",
                     "using", "several", "hours", "mute", "button", "mine", "received", "within", "hour", "owner",
                     "three",
                     "well", "even", "though", "summarize", "another", "via", "significantly", "probably", "obvious",
                     "v", "made", "certainly", "give", "nearly", "something", "almost", "3", "5", "3", "inch", "le",
                     "four",
                     "around", "edge", "tell", "seven", "sit", "simply", "underside", "allowing", "sure", "people",
                     "take",
                     "given", "20", "30", "fairly", "final", "note", "maybe", "5", "contrast", "echos", "despite",
                     "significant",
                     "either", "non", "however", "come", "5mm", "included", "nearby", "yes", "mean", "two", "one",
                     "thing",
                     "generally", "think", "primarily", "anyway", "put", "realize", "admittedly", "noticeable", "make",
                     "must", "us", "beneath", "surface", "wife", "slightly", "always", "similar", "pretty", "feet",
                     "away", "e", "direct", "angle", "pick", "obviously", "support", "example", "mind", "become",
                     "north",
                     "america", "etc", "else", "ever", "set", "personally", "fully", "including", "along", "1988",
                     "despite",
                     "republic", "dominican", "christmasnot", "130", "179", "asdfasfas", "7", "107", "⅓", "20", "hong",
                     "kong",
                     "macau", "philipe", "ohhhhh", "greatalexa", "2000", "gradually", "4th", "19th", "2017", "3rd",
                     "2014",
                     "2", "anthing", "contribute", "18ft", "36", "8", "phillip", "dozens", "candid", "jews",
                     "netherlands",
                     "millions", "1994", "3", "5", "78", "cus", "18", "17", "2013", "13", "16", "___song", "6",
                     "switzerland",
                     "d200", "5hrs", "4", "homeamazon", "5", "5mm", "180", "heretofore", "sake", "jean", "familes",
                     "buyig",
                     "8", "counld", "2016", "127", "wive", "1950", "120v", "argentina", "tu", "16", "30", "595530420",
                     "ssid", "4", "4ghz", "120", "ttype", "onlywhen", "amazonian", "enternet", "45", "pls", "400",
                     "sqft",
                     "153", "7", "2200", "680", "860", "8", "25", "109", "june", "75", "suppor", "headacheand", "75mbs",
                     "wpa", "wpa2", "sixties", "jennifer", "resulting", "bishop", "african", "increases", "10",
                     "admitted",
                     "wang", "offthe", "3", "obviousthey", "drybig", "speakerthe", "speakersave", "2", "thorough",
                     "israel",
                     "goood", "thingi", "9hr", "whis", "lest", "2017", "30th", "20017", "22" "feb", "expencive", "15",
                     "2000s",
                     "umm", "californian", "murmur", "quagmire", "addl", "nowwhere", "exactly", "way", "also",
                     "whether",
                     "u", "mexico", "canada", "saying", "close", "fox", "due", "produced", "part", "seems", "sometimes",
                     "especially", "adjacent", "assigned", "seem", "little", "let", "mostly", "whatever", "mainly",
                     "although", "already", "comes", "otherwise", "shortly", "walked", "really", "walk", "soon", "9",
                     "x", "2014", "second", "00a0", "perhaps", "going", "nothing", "seen", "therefore", "f0", "009f",
                     "94",
                     "008a", "everything", "supposed", "throughout", "based", "2", "8th", "week", "far", "84",
                     "years", "kept", "someone", "getting", "anyone", "bought", "TRUE", "least", "enough", "pull",
                     "admit", "magnet", "miss", "across", "pre", "halloween", "night", "goblin", "gone", "staff", "nov",
                     "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "dec", "plus", "increase",
                     "things",
                     "go", "lose", "seeing", "unless", "10", "20", "couple", "seemed", "sudden", "awhile", "used",
                     "sleeping",
                     "instead", "tablets", "eventually", "policy", "belonged", "year", "6th", "400", "sq", "ft", "ago",
                     "4", "together", "everywhere", "without", "next", "addition", "intended", "2016", "regard", "2017",
                     "near", "got", "5420", "5320", "ready", "october", "31st", "believe", "january", "february",
                     "march",
                     "april", "may", "june", "july", "august", "september", "november", "december", "spend", "every",
                     "felt", "knows", "yesterday", "99", "came", "unusually", "allows", "looks", "likewise",
                     "partially",
                     "8", "month", "particularly", "50", "0", "folks", "tend", "agree", "third", "minutes", "aaaaa",
                     "2018", "greate", "leve", "good", "amazing", "christmas", "better", "gift", "able", "new", "use", "nice",
					 "excellent", "great", "alexa", "gen", "generation", "love", "sound", "music", "play", "device", "work",
					 "speaker", "want", "playing", "happy", "enjoy", "best", "ask", "say", "easy", "question", "answer",
					 "product", "price", "truly", "awesome", "wish", "day", "smart", "know", "bass", "call", "feature", "features",
					 "anything", "absolutely", "easier", "star", "stars", "2nd", "since", "yet", "song", "look", "time", "old",
					 "dot", "1st", "fun", "puchased", "ok", "itwas", "ing", "fot", "008e", "dan","emensley", "add", "unit",
					 "wonderful", "phone", "weather", "ion", "1234", "br","wth","600", "5x","iftt", "cool", "voice", "find", "buy",
					 "need", "allow", "useful","ifttt", "gh", "hear", "nan", "1940", "meh", "itstill", "cannot","1933",
             "answe", "NaN", "ly", "andnot", "ghz","2007","NaN","2yo","duh","hey","nd","_________","didnt","_________","_________",
			 "iit", "01", "grr", "fori","20x","sme","rkb","inc","mbr","de","much4","000","prett","65","dotcan", "ound","hwy",
			 "deff", "responsewhat", "150mb","00am", "zz", "00a8","hue", "big", "right", "do", "fi","light", "turn","walmart", "wi",
			 "definitely","actually","back","never","original","bit","perfect","review", "wow", "wwe","yo", "yeah", "wont","won",
			 "word","wondering", "wished", "zero","sr","i", "it", "the"]
